name: Check and Format YAML files

on:
  push:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Prettier
        run: npm install --global prettier
      - name: Fix YAML formatting
        run: prettier --write '**/*.{yaml,yml}'
      - name: Check YAML formatting
        run: prettier --check '**/*.{yaml,yml}'
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: auto-format YAML files with Prettier'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install yamllint
        run: pip install yamllint
      - name: Configure yamllint to ignore document-start and truthy
        run: |
          cat <<EOF > .yamllint
          rules:
            document-start: disable
            truthy: disable
          EOF
      - name: Lint YAML files
        run: yamllint .
