name: Check YAML files

on:
  push:
    paths:
      - '**/*.yaml'
  pull_request:
    paths:
      - '**/*.yaml'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Prettier
        run: npm install --global prettier
      - name: Format YAML files
        run: prettier --write '**/*.yaml'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install yamllint
        run: pip install yamllint
- name: Configure yamllint to ignore document-start and truthy
  run: |
    echo "rules:" > .yamllint
    echo "  document-start: disable" >> .yamllint
    echo "  truthy: disable" >> .yamllint
- name: Lint YAML files
  run: yamllint .
